
export const ADOBE_STOCK_CATEGORIES = [
  'Animals',
  'Backgrounds',
  'Buildings and Architecture',
  'Business',
  'Concepts',
  'Culture and Religion',
  'Emotions',
  'Food',
  'Hobbies and Leisure',
  'Industry',
  'Landscapes',
  'Lifestyle',
  'Nature',
  'People',
  'Science',
  'Social Issues',
  'Sports',
  'Technology',
  'Transportation',
  'Travel',
  'Abstract',
];
